/* AUTO-GENERATED by tools/gen_excel_blocks.py. DO NOT EDIT. */
import meta from "./excel_funcs.meta.json";

export function registerExcelFuncGenerators(JS: any) {
  for (const fn of Object.keys(meta)) {
    const m: any = (meta as any)[fn];
    const type: string = m.block_type || `excel_fn_${fn}`;

    JS[type] = function (block: any) {
      const args: string[] = [];

      const baseNames: string[] = m.input_names || [];

      // 1) meta.input_names の順に読む
      for (const name of baseNames) {
        if (!block.getInput(name)) break;
        args.push(JS.valueToCode(block, name, JS.ORDER_NONE) || "");
      }

      // 2) 追加の可変入力（extension側が VAR_3, VAR_4... を足す想定）
      //    baseNames.length が 1 なら VAR_2 から…にしたい気持ちもあるけど、
      //    ここは extension側の命名規約に合わせる。
      //    下は「VAR_2 以降」を探す形（baseが1なら VAR_2, VAR_3...）
      for (let i = Math.max(2, baseNames.length + 1); ; i++) {
        const v = `VAR_${i}`;
        if (!block.getInput(v)) break;
        args.push(JS.valueToCode(block, v, JS.ORDER_NONE) || "");
      }

      return [`${fn}(${
        args.join(",")
      })`, JS.ORDER_ATOMIC];
    };
  }
}
